server:
  port: 7016
spring:
  application:
    name: my-wx-pay
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://wxmysql.com:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
logging:
  config: classpath:log/logback-spring.xml

wechat:
  # 公众平台授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:
  # 开发平台 ，卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
  #商户
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  #支付异步通知地址
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId: 
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
    
# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/

  
  
  
  
  

