server:
  port: 7001
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 #心跳刷新30s
    lease-expiration-duration-in-seconds: 30 #服务时效时间 等待时间
  client:
    serviceUrl:
      defaultZone: http://192.168.35.238:7000/eureka/    healthcheck:      enabled: true #配置开启健康检查，并按需配置续约更新时间和到期时间  
spring:
  application:
    name: user-service
  datasource:
    base:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.35.216:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
    licm:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.35.216:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
