server:
  port: 7006
spring:  application:    name: my-config
  cloud:    config:      server:        git:          uri: https://github.com/liuwei0815/myconfig.git
          username: 736873792@qq.com
          password: Aini200878  
          search-paths: /**  # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开       
eureka:
  instance:
    prefer-ip-address: true #主要是为了解决注册到服务器上显示为主机名的问题，一般建议显示为ip,方便区分。
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka1:7000/eureka,http://eureka2:7004/eureka,http://eureka3:7005/eureka  #设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址(服务暴露的地址)
