server:
  port: 8119
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 #心跳刷新30s
    lease-expiration-duration-in-seconds: 30 #服务时效时间 等待时间
    prefer-ip-address: true #主要是为了解决注册到服务器上显示为主机名的问题，一般建议显示为ip,方便区分。
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka1:7000/eureka,http://eureka2:7004/eureka,http://eureka3:7005/eureka  #设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址(服务暴露的地址)
    fetch-registry: true #消费端想注册中心获取服务列表请求
    registry-fetch-interval-seconds: 30 #缓存服务列表时间
spring:
  application:
    name: admin-site
  datasource:
    base:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql.com:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
    licm:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql.com:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root